# Use the official Python image
FROM python:3.11.2-slim-buster

# Set the working directory
WORKDIR /app

# Copy the neural network model script and files
COPY /src /app
COPY requirements.txt /app/requirements.txt
COPY .env.docker .env

# Install necessary Python packages
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Define the command to run your script
CMD ["python", "nn_model_main.py"]
