# Use an official Python runtime as a parent image
FROM python:3.8.3-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY /src /app
COPY requirements.txt /app/requirements.txt

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run script.py when the container launches
CMD ["python", "preprocess_main.py"]
